apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-appwrapper-controller
  namespace: tekton-pipelines
  labels:
    app: tekton-appwrapper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-appwrapper-controller
  template:
    metadata:
      labels:
        app: tekton-appwrapper-controller
    spec:
      serviceAccountName: tekton-appwrapper-controller
      containers:
      - name: controller
        image: ko://github.com/tektoncd/tekton-appwrapper/cmd/controller
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METRICS_DOMAIN
          value: tekton.dev/tekton-appwrapper
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - "ALL"
          seccompProfile:
            type: RuntimeDefault
      terminationGracePeriodSeconds: 30 
