apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: tekton-pipelines
data:
  # Metrics configuration
  metrics.backend-destination: "prometheus"
  metrics.reporting-period-seconds: "30"
  
  # Tracing configuration
  tracing.sample-rate: "0.1"
  tracing.backend: "none"
  
  # Profiling configuration
  profiling.enable: "false" 