---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-appwrapper-controller
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-appwrapper-controller
rules:
# PipelineRun permissions
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# AppWrapper permissions
- apiGroups: ["workload.codeflare.dev"]
  resources: ["appwrappers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Event permissions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# ConfigMap permissions (for both PipelineRuns and leader election)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Lease permissions for leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-appwrapper-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-appwrapper-controller
subjects:
- kind: ServiceAccount
  name: tekton-appwrapper-controller
  namespace: tekton-pipelines 