apiVersion: v1
kind: Service
metadata:
  name: tekton-appwrapper-controller
  namespace: tekton-pipelines
  labels:
    app: tekton-appwrapper-controller
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  - name: profiling
    port: 8008
    targetPort: profiling
    protocol: TCP
  selector:
    app: tekton-appwrapper-controller 